name: Nils Opie
favicon: null
layout_spectrum: 0.24316
typography_spectrum: 0.25098
title: Nils Opie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030504'
    - '#d8e51c'
    - '#fff9e9'
    - '#31460d'
    - '#85a714'
  brandStrength: 0.8125
  lightness: 0.4546580142341554
  saturation: 0.42338196840137243
  rhythmicContrast: 0.49270454864017665
purpose: []
