name: Nils Opie
favicon: null
layout_spectrum: 0.25098
typography_spectrum: 0.49804
title: Nils Opie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050608'
    - '#e4e7d4'
    - '#d6b58c'
    - '#ad8061'
    - '#38675f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
