name: Nils Opie
favicon: null
layout_spectrum: 0.25098
typography_spectrum: 0.25098
title: Nils Opie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#070906'
    - '#9c7f6f'
    - '#bfc8cf'
    - '#9d3325'
  brandStrength: 0.25
  lightness: 0.4546580142341554
  saturation: 0.42338196840137243
  rhythmicContrast: 0.49270454864017665
purpose: []
